version: '2.0'

services:  

  mongo:
    image: mongo:4
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    command: npm run dev
    restart: always
    volumes:
      - ./:/app
    environment:
      - "MONGO_HOST=mongo"
      - "HTTP_PORT=3000"
    ports:
      - 3000:3000
